# Generated by Django 4.2 on 2023-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appscoop",
            "0002_college_rename_sno_publics_studentname_staff_iiibca_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ibca",
            name="studentname",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="iibca",
            name="studentname",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="iiibca",
            name="studentname",
            field=models.CharField(default="", max_length=50),
        ),
    ]
