# Generated by Django 4.2 on 2023-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0005_alter_ibca_student_alter_iibca_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="mname",
            field=models.CharField(default="", max_length=50),
        ),
    ]
