# Generated by Django 4.2 on 2023-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0008_remove_user_roleno"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibca",
            name="roleno",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="iibca",
            name="roleno",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="iiibca",
            name="roleno",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="staff",
            name="stfid",
            field=models.CharField(default="", max_length=50),
        ),
    ]
