# Generated by Django 4.2 on 2023-05-06 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0009_ibca_roleno_iibca_roleno_iiibca_roleno_staff_stfid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="college",
            name="classname",
        ),
        migrations.RemoveField(
            model_name="college",
            name="studentname",
        ),
        migrations.AddField(
            model_name="college",
            name="student",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post_req_ibca",
            name="student",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
