# Generated by Django 4.2 on 2023-05-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "appscoop",
            "0010_remove_college_classname_remove_college_studentname_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publics",
            name="classname",
        ),
        migrations.RemoveField(
            model_name="publics",
            name="studentname",
        ),
        migrations.AddField(
            model_name="publics",
            name="imagecaption",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="publics",
            name="student",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
