# Generated by Django 4.2 on 2023-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appscoop",
            "0011_remove_publics_classname_remove_publics_studentname_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post_req_IBCA",
            new_name="Post_req",
        ),
    ]
