# Generated by Django 4.2 on 2023-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0015_college_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="title",
            field=models.CharField(default="", max_length=20),
        ),
    ]
