# Generated by Django 4.2 on 2023-05-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0016_inbox_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inbox",
        ),
    ]
