# Generated by Django 4.2 on 2023-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0019_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
