# Generated by Django 4.2 on 2023-06-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0020_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_req",
            name="status",
            field=models.CharField(default="pending", max_length=200),
        ),
    ]
