# Generated by Django 4.2 on 2023-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0022_remove_iibca_student_remove_iiibca_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(default="", max_length=4),
        ),
    ]
