# Generated by Django 4.2 on 2023-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appscoop", "0023_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(default="a", max_length=4),
        ),
    ]
